service: bot-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 256
  tracing:
    apiGateway: true
    lambda: true
  httpApi:
    payload: '1.0'
    cors:
      allowedOrigins: '*'
      allowedHeaders:
        - "Content-Type: application/json"
        - X-Amz-Date
        - Authorization
        - X-Amz-Security-Token
        - X-Amz-User-Agent
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Credentials
        - Access-Control-Allow-Methods
  environment:
    SLS_STAGE: ${self:provider.stage}
    SLS_SERVICE: ${self:service}
    GRAPHQL_ENDPOINT: ${env:GRAPHQL_ENDPOINT}
    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}
    ENCRYPTION_IV: ${env:ENCRYPTION_IV}
    HASURA_ADMIN_KEY: ${env:HASURA_ADMIN_KEY}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  main:
    handler: main.default
    events:
      - httpApi:
          method: '*'
          path: /{proxy+}
