version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5435:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "guest"
      HASURA_GRAPHQL_ADMIN_SECRET: "braksadminsecretkey"
      HASURA_GRAPHQL_JWT_SECRET: '{
      "type": "RS256",
      "key": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArOAO7xvJIAqTi9g3HcrZ\nj4dfr1wXfDQSwyAKYYOR/BABM1aOV5OJTgsC5ThfDCA+5IOAa9cbfJq5XwlgRY3O\nblyDmi+rPydxiCG1hSSA81V/ZVwRKfH8KwOE44xHYAKrNMxbcoL8P5ZWemc6EGXP\nvnimOGsE9vr0G9FjFwotxNdAGJilXfSQAVQzKz0OTExzAFapOd6RhSdJgkYHFdn3\nAJWqOWMBIfx0ipbcKPscsAMAPdMM+kFujcoYD+i2q8kTzxZS2+vIDRA9AF1rR/jU\nq1AvLQDrGdo2jTLOBLR+nMuATETWCAtzfvPJV+Ugb//tMsM8SKGLZxJ4R8OqE3PA\ncdiiFXRvLlq/APOKOa7XfaX+wZxaH+R2gbjJHymQuX0bXzcln5jErDpUsdpjNDWG\nSfAnlYBphuyPD1UzjmqeYWICygoZi0VXy4UDGWZWnzguypKaRD0/ANgbZaUuNOik\nOgTfXHwfuIvMi6CguaWBZHzELj7AoWTeKW1f5qWecSdCWwgafAtNz5lxauJ0B9LY\nEbGfDH30J08w7sxmWJ4KY8pJ/D5mrFJet5xSbDOz8ymmnNJ+SvkebXuxZ9G5EbLR\nb/X3xHSNPwIIC6CnAqgoxq71oM7mh2ry70xazByW1513jIhwMBba9aBkJuOJM4/9\nBTttVS0TB+j2QnUlYxBqLPsCAwEAAQ==\n-----END PUBLIC KEY-----\n",
      "claims_format": "json",
      "issuer": "@braks",
      "audience": ["bot-user", "bot-admin"]
      }'


